### ISSUE TITLE
LocalUser Vs. LocalVideoTrack

### ISSUE THREAD

**Issue by divanov11** [AgoraIO-Extensions/agora-rtc-react#106]
### What kind of problem do you need help?

As I understand it, it is recommended we use the `LocalVideoTrack` component instead of the `LocalUser` component. If that is so, Will `LocalVideoTrack` support properties such as:

- micOn
- cameraOn
- cover

If not, how else can we achieve tasks such as muting camera and mic, and setting the cover image?

**Comment by guoxianzhe** [comment]
@divanov11 As **hyrious** mentioned, `<LocalVideoTrack>` is a low level Component.
`agora-rtc-react` is the core and there is no plan to provide more complex components.
However, we are happy to consider that as uikit in `agora-rtc-react-ui`, but `agora-rtc-react-ui` is still under development, please look forward to our future updates.
