### ISSUE TITLE
Re export agora-rtc-sdk-ng methods from the React SDK

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/agora-rtc-react#146]
### What kind of problem does this feature solve?

Since we're positioning the React SDK as a standalone product. We should re-export all the exports from the web sdk. This is important as while using the React SDK the devs also need to access exports from Web like types, default export, enums etc.

### What does the proposed API look like?

```js
import AgoraRTC from 'agora-rtc-sdk-ng'

export default AgoraRTC;
export * from 'agora-rtc-sdk-ng';
```
Open to discuss if we should avoid a default export.

**Comment by guoxianzhe** [comment]
It can be done, but there are 2 potential problems:
1. `agora-rtc-sdk-ng` size is very large, and the way of `export *` will have a relatively large impact on the `agora-rtc-react` size
2. The independence between packages may be destroyed, and the documentation and unit testing cannot be well maintained
such as `.d.ts` should include all `agora-rtc-sdk-ng`?
3. This is not conducive to tree-shaking

**Comment by EkaanshArora** [comment]
I agree with the problems you mentioned but we're targeting to release this is as a standalone SDK, we can't position this as a dependency on the Web SDK or a wrapper. So even though the concerns you mentioned are valid, we'll have to find the best course for release

1. This is minor as if you're using this project you'd need the Web SDK installed and the bundle size would be identical in a real-life example.
2. We need to figure out what we can do here.
Yes, typings should contain all of Web SDK.
3. We can try our best here, but tree-shaking would depend on the Web SDK team to implement for us to leverage.

**Comment by guoxianzhe** [comment]
OK, please confirm is this you want? 
for example , 

old: 
```js
import AgoraRTC from "agora-rtc-sdk-ng"
````
new:
```js
import AgoraRTC from "agora-rtc-react"
```

Are you sure our users can accept this? Looks like a big change so we need to be careful.

**Comment by EkaanshArora** [comment]
Hey sorry for the wait on this. Discussing internally if we should mix both named exports and default export in the same package. This isn't considered a good practice as of late, but it follows more of the Web SDK pattern of exports so I'm torn. Which do you think is better?
```ts
import AgoraRTC, {useClientHook, ...} from "agora-rtc-react"
```
vs. 
```ts
import {AgoraRTC, useClientHook, ...} from "agora-rtc-react"
```

**Comment by guoxianzhe** [comment]
I think we should use
```js
import {AgoraRTC, useClientHook, ...} from "agora-rtc-react"
```
In case of export the default class AgoraRTCReact in the future, or we should consider (need websdk help here)

```js
export class AgoraRTCReact extends AgoraRTC {}
```
 usage:
```js
import AgoraRTCReact from "agora-rtc-react"
```


And there is more thing, [CDN](https://github.com/AgoraIO-Extensions/agora-rtc-react/blob/main/examples/mobx/index.html#L14) is umd package , window is prefer to export AgoraRTCReact instead of AgoraRTC

**Comment by EkaanshArora** [comment]
If we re-export Web SDK from React, another detail to discuss would be how we keep the Web SDK peer dependency up to date. We'll need to make sure that minor updates to the Web SDK don't require an update to the React SDK. New installs of the React SDK should get the latest releases of both (as long as Web SDK follows semantic versioning/backwards compatibility). This shouldn't be difficult to do, just something to keep in mind when we make this change.

**Comment by EkaanshArora** [comment]
Argument against default exports: https://x.com/kentcdodds/status/1702339919438627290

**Comment by guoxianzhe** [comment]
@EkaanshArora  I did some for this feature,  #163 


<img width="775" alt="image" src="https://github.com/AgoraIO-Extensions/agora-rtc-react/assets/53285945/0aee6ff3-b072-4d4e-a8ed-cf4dfc6e8fd2">


And window object (only in umd/iife)
<img width="1089" alt="企业微信截图_67e3433b-97b8-4566-83ed-f7b21c5211c6" src="https://github.com/AgoraIO-Extensions/agora-rtc-react/assets/53285945/c7dee64d-04e0-4354-b398-bc0e0e30f1f2">


Let me know if you have another ideas.

**Comment by EkaanshArora** [comment]
Hey this looks good, let me give it a try and get back to you!

**Comment by guoxianzhe** [comment]
completed in #163
