### ISSUE TITLE
Document potential pitfall of useLocalMicrophoneTrack & useLocalCameraTrack

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/agora-rtc-react#147]
### What kind of problem does this feature solve?

We create tracks using `useLocalMicrophoneTrack` and `useLocalCameraTrack`, it returns the same track within the component, but creates a new track when called in a different component down the React tree. This behavior is useful for creating multiple tracks, but can be a common pitfall.

### What does the proposed API look like?

I'd like to document in the code comment about this behavior. Happy to make a PR for this myself.

**Comment by guoxianzhe** [comment]
@EkaanshArora 

This is a good idea. Can you provide a pr to make this happen? Thanks.

**Comment by dengyaxi** [comment]
Hi @EkaanshArora Just want to check if you encounter any problem making this PR. You can make a PR in this repo and I'll sync the updates to the official website. Let us know!

**Comment by EkaanshArora** [comment]
Added #168, please review

**Comment by dengyaxi** [comment]
Thank you. I left a comment in the PR
