### ISSUE TITLE
black screen issue

### ISSUE THREAD

**Issue by yerinkim-fe** [AgoraIO-Extensions/agora-rtc-react#158]
### What kind of problem do you need help?

If a MacBook user closes and opens the MacBook during a video call, the videoTrack appears black. 
In the log, document camera device changed  
"state":"INACTIVE" -> "ACTIVE"
document visibility went hidden -> visible
But the screen is still black
How can I fix this?

`When the SDK triggers the localTrack.on("track-ended") event, use a popup window to remind the end user to check whether the device is working or to reconnect the device.`

no popup window

**Comment by guoxianzhe** [comment]
@yerinkim-fe  You should create a popup window by yourself. SDK will not handle this action. You can use 

```jsx
useTrackEvent(track, "track-ended", () => { 
  //show popup or something  
}); 
```

**Comment by yerinkim-fe** [comment]
@guoxianzhe Thanks for the reply
I'm trying to use onCameraChanged, is it defined in this package? I can't find it!

**Comment by guoxianzhe** [comment]
@yerinkim-fe 

more flexible way:

``` tsc
AgoraRTC.on("camera-changed", (changedDevice) => {
  // When plugging in a device, switch to a device that is newly plugged in.
    if (changedDevice.state === 'ACTIVE') {
      void localCameraTrack?.setDevice(changedDevice.device.deviceId);
    }
});
```
