### ISSUE TITLE
I can hear myself while I am alone in the room.

### ISSUE THREAD

**Issue by Azm3n** [AgoraIO-Extensions/agora-rtc-react#179]
### What kind of problem do you need help?

Whenever I join video I can hear myself and I don't know how to turn off such behaviour. I copied code from this code sandbox - https://codesandbox.io/p/sandbox/agora-rtc-react-quickstart-rdpc46?file=%2Fsrc%2FApp.js. Is there any option that I am missing?

**Comment by guoxianzhe** [comment]
@Azm3n <LocalUser/> Component add attributes `playAudio` to `false`

eg: `<LocalUser playAudio={false} />`
