### ISSUE TITLE
window is not defined error when integrating with nextjs

### ISSUE THREAD

**Issue by yinjs** [AgoraIO-Extensions/agora-rtc-react#181]
### What kind of problem do you need help?

"window is not defined" error when integrating with nextjs

<img width="656" alt="Screenshot 2024-01-08 at 14 31 35" src="https://github.com/AgoraIO-Extensions/agora-rtc-react/assets/9780399/2189194d-a55b-49fa-922a-ed08e88350a8">

Sandbox to reproduce the issue
[https://codesandbox.io/p/devbox/agora-rtc-react-6x58n8](https://codesandbox.io/p/devbox/agora-rtc-react-6x58n8)

**Comment by guoxianzhe** [comment]
It seems you are running sdk in server side. you can use [dynamically import](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading) like this:

  ```
useEffect(() => {
    const initSdk = async () => {
      const AgoraRTC = (await import("agora-rtc-react")).default;
      const client = AgoraRTC.createClient({ mode: "live", codec: "vp8" });
    };
    initSdk();
  }, []);
```

**Comment by yinjs** [comment]
@guoxianzhe Had tried your solution. Still get same error. Tried some other ways like `const isBrowser = () => typeof window !== "undefined";`. No luck. Lol...

**Comment by guoxianzhe** [comment]
@yinjs pls follow [this](https://codesandbox.io/p/devbox/agora-rtc-react-forked-xsy24z?file=%2Fapp%2Fproviders.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr7xn4ce0007356ixvw655jr%2522%252C%2522sizes%2522%253A%255B80.39786934490428%252C19.60213065509572%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr7xn4ce0002356izr39w0wi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr7xn4ce0004356ifukm6i08%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr7xn4ce0006356is14k5ojc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B68.09312172095042%252C31.90687827904958%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr7xn4ce0002356izr39w0wi%2522%253A%257B%2522id%2522%253A%2522clr7xn4ce0002356izr39w0wi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7xn4ce0001356i6wfvuocz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.next%252Fserver%252Fwebpack-runtime.js%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A33%252C%2522endLineNumber%2522%253A33%252C%2522startColumn%2522%253A42%252C%2522endColumn%2522%253A42%257D%255D%252C%2522id%2522%253A%2522clr7xqo9900jy356ishlr4eqm%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr7xn4ce0001356i6wfvuocz%2522%257D%252C%2522clr7xn4ce0006356is14k5ojc%2522%253A%257B%2522id%2522%253A%2522clr7xn4ce0006356is14k5ojc%2522%252C%2522activeTabId%2522%253A%2522clr7xuk0a01cu356i1hisgzly%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clr7xuk0a01cu356i1hisgzly%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr7xn4ce0004356ifukm6i08%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7xn4ce0003356imrttq7rt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clr7xn4ce0004356ifukm6i08%2522%252C%2522activeTabId%2522%253A%2522clr7xn4ce0003356imrttq7rt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 
Or you can create a component that has this import in the component and then use `next/dynamic` with `ssr: false` as you had tried

**Comment by yinjs** [comment]
@guoxianzhe thanks! 

pasted my version in case someone need this.
```typescript
// AgoraRTCProvider.tsx

"use client";
import { useState, useEffect, ReactNode, useRef } from "react";
import type { ClientConfig, IAgoraRTCClient } from "agora-rtc-react";
import dynamic from "next/dynamic";

const AgoraRTCProviderPrimitive = dynamic(
  () =>
    import("agora-rtc-react").then(({ AgoraRTCProvider }) => AgoraRTCProvider),
  {
    ssr: false,
  },
);

export default function AgoraRTCProvider(props: {
  clientConfig: ClientConfig;
  children: ReactNode;
}) {
  const clientConfigRef = useRef<ClientConfig>(props.clientConfig);
  const [client, setClient] = useState<IAgoraRTCClient>();

  useEffect(() => {
    const initSdk = async () => {
      const AgoraRTC = (await import("agora-rtc-react")).default;
      setClient(AgoraRTC.createClient(clientConfigRef.current));
    };
    initSdk();
  }, []);

  return (
    client && (
      <AgoraRTCProviderPrimitive client={client}>
        {props.children}
      </AgoraRTCProviderPrimitive>
    )
  );
}
```

**Comment by Josh-Savvy** [comment]
> ```ts
> import { useState, useEffect, ReactNode, useRef } from "react";
> import type { ClientConfig, IAgoraRTCClient } from "agora-rtc-react";
> import dynamic from "next/dynamic";
> 
> const AgoraRTCProviderPrimitive = dynamic(
>   () =>
>     import("agora-rtc-react").then(({ AgoraRTCProvider }) => AgoraRTCProvider),
>   {
>     ssr: false,
>   },
> );
> 
> export default function AgoraRTCProvider(props: {
>   clientConfig: ClientConfig;
>   children: ReactNode;
> }) {
>   const clientConfigRef = useRef<ClientConfig>(props.clientConfig);
>   const [client, setClient] = useState<IAgoraRTCClient>();
> 
>   useEffect(() => {
>     const initSdk = async () => {
>       const AgoraRTC = (await import("agora-rtc-react")).default;
>       setClient(AgoraRTC.createClient(clientConfigRef.current));
>     };
>     initSdk();
>   }, []);
> 
>   return (
>     client && (
>       <AgoraRTCProviderPrimitive client={client}>
>         {props.children}
>       </AgoraRTCProviderPrimitive>
>     )
>   );
> }
> ```

Hi @yinjs, I'm having a similar issue, and this solution doesn't seem to be effective.

ERR: ReferenceError: window is not defined
    at new <anonymous> (/User......)

**Comment by yinjs** [comment]
@Josh-Savvy did you use impot ... from 'agora-rtc-react' some where before this Provider load?

**Comment by Josh-Savvy** [comment]
> @Josh-Savvy did you use impot ... from 'agora-rtc-react' some where before this Provider load?

Yeah, that was the issue, I forgot that I'd imported the AgoraRTCProvider directly in the layout.tsx before I found this solution. Thank you

**Comment by Josh-Savvy** [comment]
> @Josh-Savvy did you use impot ... from 'agora-rtc-react' some where before this Provider load?

@yinjs Yeah, that was the issue, I forgot that I'd imported the AgoraRTCProvider directly in the layout.tsx before I found this solution. Thank you
