### ISSUE TITLE
useRemoteUsers returns empty array

### ISSUE THREAD

**Issue by Azm3n** [AgoraIO-Extensions/agora-rtc-react#183]
### What kind of problem do you need help?

I use agora in a React web app and a Flutter mobile app. When I join a channel on the website and mobile app only on mobile, I can see and hear the customer from a different device. I tried to fix it and found that useRemoteUsers does not return any client. What could be the reasons for this behavior?

I am using agora-rtc-react version 2.1.0 and it is code for React that I was taking inspiration from https://codesandbox.io/p/sandbox/agora-rtc-react-quickstart-rdpc46

**Comment by guoxianzhe** [comment]
@Azm3n `useRemoteUsers` hooks only return users data when :

 * When a remote user joins or leaves the channel.
 * When the role of a remote user changes (for example, from broadcaster to audience).
 * When a remote user publishes or unpublishes the audio or video track.

https://github.com/AgoraIO-Extensions/agora-rtc-react/blob/main/packages/agora-rtc-react/src/hooks/useRemoteUsers.ts#L11

**Comment by Azm3n** [comment]
I completely understand it. I haven't changed anything from mobile flow because when I was using agora-rtc-react < 2.0.0 it was working. When I decided to change versions I started using useRemoteUsers and even though the flow from mobile app hasn't changed it is not returning expected mobile user in React app. Are there any other ways to retrieve remote clients?

**Comment by guoxianzhe** [comment]
@Azm3n You can use `useClientEvent` to retrieve remote clients by yourself.

eg: 
```jsx
const client = useRTCClient();
useClientEvent(client,'user-published',(user)=>{
    console.log('user:',user)
})
```

**Comment by Azm3n** [comment]
It was all about uid. React app was sending string type and mobile app was sending number. Thank you!!
