### ISSUE TITLE
renewToken() method failed

### ISSUE THREAD

**Issue by qq8721443** [AgoraIO-Extensions/agora-rtc-react#184]
### What kind of problem do you need help?

First of all, I'm not good at English, so some sentances are strange or rude... Please understand. I'm new to Agora and using agora-rtc-react for making voice calling with React web. Now I'm trying to renew my agora token that I got issued when entering a voice channel. So using agoraClient's renewToken() method, but it doesn't work. I got the error below.

```Agora-SDK [ERROR]: data: {"code":110,"data":{"error_code":110,"error_str":"error to verify token permission"}} AgoraRTCException: AgoraRTCError UNEXPECTED_RESPONSE: ERR_NO_AUTHORIZED: error to verify token permission```

And here's my code.

```javascript
useClientEvent(agoraEngine, "token-privilege-will-expire", async () => {
   try {
      console.log("renew token");

      const { data } = await axios.post(
        "[[ My Token Server Host ]]",
        undefined,
        {
          headers: {
            Authorization: `Bearer ${tempToken}`,
          },
        }
      ); // succeed
    
      await agoraEngine.renewToken(data.data.token); // failed
    } catch (e) {
      console.error(e);
    }
});
```
Getting new token was succeed, but renew token was failed. I've tried to find any articles or questions but couldn't found. What is wrong and How can I fix this error?

I tried to figure out the token is valid, I used that new token to join the channel and it worked as well. Only Using renewToken() method is problem.

**Comment by guoxianzhe** [comment]
@qq8721443 It seems your token is invalid, please check your token and check [this page](https://docs-legacy.agora.io/en/Lecture%20Hall/faq/token_error)

**Comment by qq8721443** [comment]
@guoxianzhe Thanks for comment! First I thought my token is invalid, so checked that document but I couldn't find a solution. I'm using the same token server in web and flutter app, flutter's renewToken works well but web doesn't. And the token that I reissued in web works well when joining the channel 😢 Can it be possible?

It's my first time to ask question to package contributers, so if I was wrong please let me know 🙇

**Comment by ltsg123** [comment]
Can you provide your uid and cname when reproducing the problem? @qq8721443

**Comment by qq8721443** [comment]
@ltsg123 Of course! My uid is `1030526566` and cname is `018d5fa9-e6a5-13b0-8457-7627140f630c`.
FYI, My backend team said that they use wildcard channel ('*') to create tokens!

Thanks for your help 👍

**Comment by qq8721443** [comment]
OMG it works! When I used channel-specified token, renewToken() works well. Using wildcard token to join a channel works, so I didn't figure out that wildcard causes this problem. Thank you so much @Winter-Win! Could you share a documentation about it please? I only found about renewToken() method.

<img width="940" alt="스크린샷 2024-02-06 오전 11 19 45" src="https://github.com/AgoraIO-Extensions/agora-rtc-react/assets/61747121/07200b78-2e3b-4da6-980a-47b9b757436d">

**Comment by guoxianzhe** [comment]
@qq8721443 We will consider your advice and add it in the future if necessary.
