### ISSUE TITLE
AgoraRTCError INVALID_PARAMS: parameter is not local track

### ISSUE THREAD

**Issue by joshbenandiel** [AgoraIO-Extensions/agora-rtc-react#185]
### What kind of problem do you need help?

Here's my config:  AgoraRTC.createClient({ mode: "live", codec: "h264" });

Why I'm getting this error when i try to publish audio track?

```
 const client = useRTCClient();
 const { localMicrophoneTrack } = useLocalMicrophoneTrack();
 
 client?.publish([localMicrophoneTrack]);
```
 
 this code triggers the error

**Comment by guoxianzhe** [comment]
@joshbenandiel , I have been on vacation and sorry for the late reply.

Can you tell me 

1. which version of agora-rtc-react you are using?
2. Did you call `setClientRole` before publish the track?

**Comment by joshbenandiel** [comment]
Hi @guoxianzhe yeah this works but it is possible i can publish track with uid as string?

`usePublish([localMicrophoneTrack], true);`

`AgoraRTCException: AgoraRTCError INVALID_PARAMS: invalid id: the value range is [0, 65535]. integer only`

base on your docs uid can be string or number right?
thanks

**Comment by joshbenandiel** [comment]
`agora-rtc-react": "2.1.0",`

Here's the version i use

**Comment by guoxianzhe** [comment]
@joshbenandiel 

1. If you added `agora-rtc-sdk-ng` in your package.json, please remove it. Since 2.0.0, you no longer need to add `agora-rtc-sdk-ng` in your own package.json.
2. You can use string uid when you call `client.join`, please make sure you pass a string type uid.

**Comment by joshbenandiel** [comment]
i see it works now thank you! i get it now @guoxianzhe

**Comment by joshbenandiel** [comment]
Maybe my last question is how can i unpublish stream in `agora-rtc-react`? I can't find any thank you

**Comment by guoxianzhe** [comment]
@joshbenandiel 

please refer https://api-ref.agora.io/en/video-sdk/web/4.x/interfaces/ilocalaudiotrack.html#setmuted

**Comment by DasGandlaf** [comment]
> @joshbenandiel
> Since 2.0.0, you no longer need to add `agora-rtc-sdk-ng` in your own package.json.

Side point, I've encountered this issue because this blog still says to download `agora-rtc-sdk-ng`.
https://www.agora.io/en/blog/agora-react-sdk-build-a-video-conferencing-app-in-minutes/

You guys might want to remove that. Thanks for helping us out!
