### ISSUE TITLE
How to play remote video with objectFit: 'contain',

### ISSUE THREAD

**Issue by nileshzala005** [AgoraIO-Extensions/agora-rtc-react#186]
### What kind of problem do you need help?

This hooks  [useRemoteUsers](https://github.com/AgoraIO-Extensions/agora-rtc-react/tree/main/packages/agora-rtc-react/docs/hooks/useRemoteUsers.en-US.mdx)  return  remote users list with remote video track 
   const remoteUsers = useRemoteUsers();

How to play remote video track with objectFit: 'contain', using [RemoteUser](https://github.com/AgoraIO-Extensions/agora-rtc-react/tree/main/packages/agora-rtc-react/docs/components/RemoteUser.en-US.mdx) component 

Agora Play Doc link https://api-ref.agora.io/en/voice-sdk/web/4.x/interfaces/iremotevideotrack.html#play

**Comment by guoxianzhe** [comment]
@nileshzala005 Currently, [RemoteUser](https://github.com/AgoraIO-Extensions/agora-rtc-react/blob/main/packages/agora-rtc-react/docs/components/RemoteUser.en-US.mdx) can not set `objectFit` , We will add this feature in next version.
You can use [css](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) to control it by yourself temporary.

eg: 
```css
YOUR VIDEO {
    object-fit: contain!important;
}
```
