### ISSUE TITLE
How to identify track is normal video track or shared screen ?

### ISSUE THREAD

**Issue by nileshzala005** [AgoraIO-Extensions/agora-rtc-react#187]
### What kind of problem do you need help?

This hooks [useRemoteUsers](https://github.com/AgoraIO-Extensions/agora-rtc-react/tree/main/packages/agora-rtc-react/docs/hooks/useRemoteUsers.en-US.mdx) return remote users list with remote video track and shared screen track
const remoteUsers = useRemoteUsers();

How to identify track is normal video track or shared screen ?

**Comment by guoxianzhe** [comment]
@nileshzala005 

check the [sample code](https://github.com/AgoraIO-Extensions/agora-rtc-react/blob/main/examples/basic/src/pages/advanced/share-screen/index.tsx#L42)  you can identify by UID.

**Comment by ttebify** [comment]
Like @guoxianzhe mentioned, you can identify by UID.

Here is another creative approach. On your server, embed some information into the token to identify a screen share client and retrieve the token via UID. Decode and use it normally. Here is an example:

```ts
client.on("user-published", async (participant, mediaType) => {
    const remoteId = participant.uid as string;
    const clientData = decodeData(remoteId);

    if (clientData?.id !== user?.id) {
        await client.subscribe(participant, mediaType);

        if (mediaType === "audio") {
            participant.audioTrack?.play();
        }
    }

    if (clientData?.screen_share) { // Here I know it is a screen share client
        setHighlightedParticipant(remoteId);
    }
});
```

Here is a reference to see how this token can be created on the server:
https://github.com/AgoraIO-Extensions/agora-rtc-react/issues/199#issuecomment-2260876956
