### ISSUE TITLE
There are errors shown in the console when running in the Firefox browser

### ISSUE THREAD

**Issue by taitruong007** [AgoraIO-Extensions/agora-rtc-react#188]
### What kind of problem do you need help?

Thank you for the great package!
I've found these errors when trying the demo site in the Firefox browser.

<img width="1512" alt="Screen Shot 2024-03-30 at 13 51 33" src="https://github.com/AgoraIO-Extensions/agora-rtc-react/assets/112865849/cdc633f6-2c5c-4518-b3a5-6a707de0e70e">

The Firefox version:

<img width="736" alt="Screen Shot 2024-03-30 at 13 57 54" src="https://github.com/AgoraIO-Extensions/agora-rtc-react/assets/112865849/11844f90-2480-4472-a5e5-bb34423923c4">

Could you please give me your opinion about this?

**Comment by guoxianzhe** [comment]
@taitruong007 Are you encountering any problems now? For example, you can't hear the other party's voice or camera? Apart from this error, I saw in the log that the connection has been established normally.

**Comment by taitruong007** [comment]
> @taitruong007 Are you encountering any problems now? For example, you can't hear the other party's voice or camera? Apart from this error, I saw in the log that the connection has been established normally.

Thank you for your reply!
I can hear the other party's voice or camera, the features seem to be working fine!
It's just about the errors that are showing in the Firefox browser only.

**Comment by guoxianzhe** [comment]
@taitruong007 I asked our teams and they said it's everything fine and if you have any questions, please feel free to ask again.
