### ISSUE TITLE
How to use `agora-rtc-sdk-ng-fake` package together with `agora-rtc-react`?

### ISSUE THREAD

**Issue by taitruong007** [AgoraIO-Extensions/agora-rtc-react#191]
### What kind of problem do you need help?

Currently, I'm using `agora-rtc-react` in my project, and I want to use [agora-rtc-sdk-ng-fake](https://github.com/AgoraIO-Extensions/agora-rtc-sdk-ng-fake) as well because its utilities for writing tests are pretty good.
Could you please show me how I can achieve this?

**Comment by guoxianzhe** [comment]
@taitruong007 [agora-rtc-sdk-ng-fake](https://github.com/AgoraIO-Extensions/agora-rtc-sdk-ng-fake) is a internal package. 
It hasn't been published to npm, you can only import it as a dependency from GitHub directly. If you're using Vitest, you can reference [package.json](https://github.com/AgoraIO-Extensions/agora-rtc-react/blob/main/package.json#L75)and [test](https://github.com/AgoraIO-Extensions/agora-rtc-react/tree/main/packages/agora-rtc-react/test) for configuration. 
If you're using Jest, you can refer to the [iris_web](https://github.com/AgoraIO-Extensions/iris_web/blob/main/packages/rtc/test/impl/IAgoraRtcEngineImpl.test.ts#L4) for configuration.
