### ISSUE TITLE
Issue with Audio Communication at agora-rtc-react v1.1.3

### ISSUE THREAD

**Issue by serasdf** [AgoraIO-Extensions/agora-rtc-react#194]
### What kind of problem do you need help?

We are using the following versions:

```
"agora-rtc-react": "^1.1.3"
"agora-rtc-sdk-ng": "^4.18.2"
```

Until last year, both video and audio were functioning well in our video chat feature. However, during recent tests, we encountered a bug where the video works fine, but the audio is not transmitting.

We noticed that v2 has been officially released. Does this mean that version 1 of agora-rtc-react is no longer supported at all?
Is there any solution to this issue?

**Comment by guoxianzhe** [comment]
@serasdf v1 version has been archived on Dec 6, 2023. Please migration to v2 version.
