### ISSUE TITLE
useJoin hook returning isConnected false

### ISSUE THREAD

**Issue by parvez-144** [AgoraIO-Extensions/agora-rtc-react#202]
### What kind of problem do you need help?

I am using agora for adding group video call feature, however i am using websockets for a real time whiteboard sharing and real time messaging.When i comment out my socket code ,agora's useJoin hook is working properly but when i also activate my socket i am having trouble in joining channel as use Join returns some data but "isConneted :false".
![Screenshot 2024-07-21 182608](https://github.com/user-attachments/assets/898a449f-17df-4cb2-afbf-ae483a901a8b)
this is my socket part.
![Screenshot 2024-07-21 182132](https://github.com/user-attachments/assets/7c6c677d-08ee-42a8-9ba4-12a654626026)
and this is how i am using agora for video sharing.
![lobby](https://github.com/user-attachments/assets/ffc6a915-381d-42e5-a4a9-d028dc7ef854)
when i comment out my socket's enippet it works.Please help to come out of this issue and let me know if any additional info i can provide.

**Comment by guoxianzhe** [comment]
@parvez-144 Can you tell me what 
```
socket.emit("")
```
did? Is that agora's api?

**Comment by parvez-144** [comment]
No its not agora's api i am using different websocket to implement messaging.so socket.emit triggers a event to our server when a user joins room and then server broadcasts that info to all other participants in the room that this person joined or left the room.

**Comment by guoxianzhe** [comment]
@parvez-144 Can you show the logs when you can't join rooms

**Comment by guoxianzhe** [comment]
Closed due to no response from the original author. Please feel free to reopen it if you have more information that can help us investigate the issue further.
