### ISSUE TITLE
AgoraRTCReactException: Super constructor null of Sl is not a constructor.

### ISSUE THREAD

**Issue by abu-noman30** [AgoraIO-Extensions/agora-rtc-react#206]
### What kind of problem do you need help?

I'm facing an issue with Agora video calling in my production environment. I'm using Agora-RTC-React v2.1.0 and Next.js v14.1.3 for a video calling feature in my app.

The problem occurs only after deployment to production. In my local development environment, everything works perfectly, and video calls run smoothly. However, after deploying to production, the following error shows up in the browser console:

![Screenshot 2024-09-18 030437](https://github.com/user-attachments/assets/0404b98a-5202-466b-9f1f-4f9168831495)

Since the createCameraVideoTrack  function fails due to this error, it is unable to access or create the camera track, leading to the camera not functioning.

**Comment by abu-noman30** [comment]
Using Next.js v14.2.12 with agora-rtc-react v2.3.0 resolves the issue. The application runs smoothly in both development and production environments.

At Next.js v14.1.3 which version of agora-rtc-react is applicable?

**Comment by guoxianzhe** [comment]
@abu-noman30 you can use  `agora-rtc-react@2.3.0`

**Comment by abu-noman30** [comment]
@guoxianzhe with Next.js v14.1.3  rtc-react v2.1.0 / v2.2.0/  v2.3.0 all occuring same error.

**Comment by abu-noman30** [comment]
@guoxianzhe how?

**Comment by guoxianzhe** [comment]
@abu-noman30 Can you provide a repro project for this?

**Comment by guoxianzhe** [comment]
@digz6666 I tested nextjs@13.5.7 and agora-rtc-react@latest, everything is ok.

@abu-noman30 I think this is nextjs bug and i tested nextjs@14.2.x has been fixed this issue.

**Comment by guoxianzhe** [comment]
Guys, If you still have problems with nextjs, you can try this workaround:
https://github.com/THEOplayer/samples-nextjs/commit/440aab674a871e8bb8745d53c2372a4f769fef67
